all: 
	$(MAKE) -C glew-1.7.0
	$(MAKE) -C VoxVizCore
	$(MAKE) -C VoxVizOpenGL
	$(MAKE) -C MarchingCubes
	$(MAKE) -C VolumeSlicer3D
	$(MAKE) -C RayCaster
	$(MAKE) -C GigaVoxels
	$(MAKE) -C VoxVizViewer

clean:
	$(MAKE) -C glew-1.7.0 $@
	$(MAKE) -C VoxVizCore $@
	$(MAKE) -C VoxVizOpenGL $@
	$(MAKE) -C MarchingCubes $@
	$(MAKE) -C VolumeSlicer3D $@
	$(MAKE) -C RayCaster $@
	$(MAKE) -C GigaVoxels $@
	$(MAKE) -C VoxVizViewer $@
    
